name: Format code
on:
  pull_request:
    branches: [main,]
  push:
    branches: [main,]
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: psf/black@stable
        with:
          options: "--verbose"
#          src: "pychron/"
#      - uses: rickstaa/action-black@v1
#        with:
#          black_args: " pychron/**/*.py "
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with:
          commit_message: Formatting changes
          branch: ${{ github.head_ref }}